
service: banter-api-serverless

provider:
  name: aws
  stage: dev
  region: us-east-1

package:
  individually: true

functions:
  HelloWorld:
    runtime: nodejs6.10
    handler: lambdas/hello-world/handler.handler
    package:
      include:
        - lambdas/hello-world/**
    events:
      - http:
          path: hello
          method: GET
          authorizer: AuthorizerFunc

  AddAccount:
    runtime: nodejs6.10
    handler: lambdas/account/add/handler.handler
    package:
      include:
        - lambdas/account/add/**
    events:
      - http:
          path: account/add
          method: POST
          authorizer: AuthorizerFunc

  RegisterUser:
    # runtime: python3.6
    # handler: lambdas/cognito/post-confirm-sign-up-user/handler.handler
    # package:
    #   include:
    #     - lambdas/cognito/post-confirm-sign-up-user/**
    runtime: nodejs6.10
    handler: lambdas/cognito/post-confirm-sign-up-user/handler.handler
    package:
      include:
        - lambdas/cognito/post-confirm-sign-up-user/handler.js
    events:
      - http:
          path: user/register
          method: POST

  AuthorizerFunc:
    runtime: nodejs6.10
    handler: lambdas/authorizer/handler.handler
    package:
      include:
        - lambdas/authorizer/**
