
service: banter-api-serverless

provider:
  name: aws
  stage: dev
  region: us-east-1

plugins:
  - serverless-sam

package:
  individually: true

functions:
  HelloWorld:
    runtime: nodejs6.10
    handler: lambdas/hello-world/handler.handler
    package:
      include:
        - lambdas/hello-world/**
    events:
      - http:
          path: hello
          method: GET
          authorizer: AuthorizerFunc

  AddAccount:
    runtime: nodejs6.10
    handler: lambdas/account/add/handler.handler
    package:
      include:
        - lambdas/account/add/**
    events:
      - http:
          path: account/add
          method: POST
          authorizer: AuthorizerFunc

  AuthorizerFunc:
    runtime: nodejs6.10
    handler: lambdas/authorizer/handler.handler
    package:
      include:
        - lambdas/authorizer/**
